USE [master]
GO
IF NOT EXISTS(SELECT top 1 1 FROM sys.databases WHERE name = 'TestCompanyDb')
BEGIN
/****** Object:  Database [TestCompanyDb]    Script Date: 2018/11/08 16:01:27 ******/
CREATE DATABASE [TestCompanyDb]

END

ALTER DATABASE [TestCompanyDb] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestCompanyDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestCompanyDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestCompanyDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestCompanyDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestCompanyDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestCompanyDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestCompanyDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestCompanyDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestCompanyDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestCompanyDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestCompanyDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestCompanyDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestCompanyDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestCompanyDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestCompanyDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestCompanyDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TestCompanyDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestCompanyDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestCompanyDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestCompanyDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestCompanyDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestCompanyDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestCompanyDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestCompanyDb] SET RECOVERY FULL 
GO

ALTER DATABASE [TestCompanyDb] SET  MULTI_USER 
GO

ALTER DATABASE [TestCompanyDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestCompanyDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestCompanyDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestCompanyDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestCompanyDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestCompanyDb] SET QUERY_STORE = OFF
GO

USE [TestCompanyDb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TestCompanyDb] SET  READ_WRITE 
GO


