USE [TestCompanyDb]
GO
IF NOT EXISTS (SELECT TOP 1 1 FROM sys.tables where name = 'Employee')
BEGIN
CREATE TABLE Employee(
Id INT NOT NULL IDENTITY(1,1),
FirstName NVARCHAR(255) NOT NULL,
LastName NVARCHAR(255) NOT NULL,
ComplexDetails NVARCHAR(255) NULL,
StreetName NVARCHAR(255) NOT NULL,
Suburb NVARCHAR(255) NOT NULL,
Province NVARCHAR(255) NOT NULL,
Country NVARCHAR(255) NOT NULL,
PostalCode NVARCHAR(20) NOT NULL,
ContactCountryCode NVARCHAR(3) NOT NULL,
ContactNumber NVARCHAR(14) NOT NULL,
ContactExtension NVARCHAR(4) NULL,
EmailAddress NVARCHAR(100) NULL,
TwitterHandle NVARCHAR(100) NULL,
GithubPage NVARCHAR(100) NULL,
CreatedOn DATETIME2 NOT NULL CONSTRAINT df_Employee_CreatedOn  DEFAULT SYSDATETIME() ,
CreatedByUser INT NULL,
UpdatedOn DATETIME2 NOT NULL CONSTRAINT df_Employee_UpdatedOn  DEFAULT SYSDATETIME() ,
UpdatedByUser INT NULL
CONSTRAINT PK_Employee_Id PRIMARY KEY(Id)
)
END
